FROM node:11.12.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci
RUN npm install react
RUN npm install react-scripts@2.1.8 -g --silent

CMD ["npm", "start"]
